// Script: enrich data.js nodes with photos, papers, channel YouTube links,
// and coherence complements. Mutates data.js in place (same pattern as
// add_en_translations.js). Re-runnable.
//
// Run from: PAGINA WEB/web/
// Usage: node enrich-data.js
//
// NOTE: data.js is generated by scripts/build-data.js and then post-processed
// by the translation scripts (add_en_*.js) and this script. If you ever re-run
// `npm run build`, re-apply the _en scripts and this one afterwards.

const fs = require('fs');
const path = require('path');
const filePath = path.join(__dirname, 'data.js');
const content = fs.readFileSync(filePath, 'utf8');
const i = content.indexOf('{');
const j = content.lastIndexOf('}');
const data = JSON.parse(content.slice(i, j + 1));

// ── 1. PHOTOS (face thumbnails in assets/faces/) ────────────────────────────
// Auto-detected: any file named <node.id>.(jpg|jpeg|png|webp) inside
// assets/faces/ is mapped to that node. Drop a new face in there (named after
// the node id) and re-run this script — no edits needed.
// Current images sourced from Wikipedia/Wikimedia Commons (free/Commons images).
const FACES_DIR = path.join(__dirname, 'assets', 'faces');
const PHOTOS = {};
if (fs.existsSync(FACES_DIR)) {
  for (const f of fs.readdirSync(FACES_DIR)) {
    const m = f.match(/^(.+)\.(jpg|jpeg|png|webp)$/i);
    if (m) PHOTOS[m[1]] = 'assets/faces/' + f;
  }
}

// ── 2. PAPERS / PATENTS (scientists) ────────────────────────────────────────
// Official published papers, peer-reviewed articles and granted patents.
const PAPERS = {
  salvatore_pais: [
    { titulo: 'Craft Using an Inertial Mass Reduction Device (US10144532B2, US Navy)', url: 'https://patents.google.com/patent/US10144532B2/en' },
    { titulo: 'High Frequency Gravitational Wave Generator (US10322827B2, US Navy)', url: 'https://patents.google.com/patent/US10322827B2/en' },
    { titulo: 'Plasma Compression Fusion Device (US20190295733A1, US Navy)', url: 'https://patents.google.com/patent/US20190295733A1/en' }
  ],
  hal_puthoff_y_el_programa_baass: [
    { titulo: 'Polarizable-Vacuum (PV) representation of general relativity (1999)', url: 'https://arxiv.org/abs/gr-qc/9909037' },
    { titulo: 'Information transmission under conditions of sensory shielding (Nature, 1974)', url: 'https://www.nature.com/articles/251602a0' }
  ],
  russell_targ: [
    { titulo: 'Information transmission under conditions of sensory shielding (Nature, 1974)', url: 'https://www.nature.com/articles/251602a0' }
  ],
  eric_w_davis: [
    { titulo: 'Teleportation Physics Study (Air Force Research Laboratory, 2004)', url: 'https://www.theblackvault.com/documentarchive/teleportation-physics-study-air-force-research-laboratory-august-2004-dr-eric-w-davis/' }
  ],
  prof_garry_nolan: [
    { titulo: 'Improved instrumental techniques, including isotopic analysis, applicable to the characterization of unusual materials (Progress in Aerospace Sciences, 2022)', url: 'https://doi.org/10.1016/j.paerosci.2021.100788' }
  ],
  jacques_vallee: [
    { titulo: 'Improved instrumental techniques, including isotopic analysis, applicable to the characterization of unusual materials (Progress in Aerospace Sciences, 2022)', url: 'https://doi.org/10.1016/j.paerosci.2021.100788' }
  ],
  avi_loeb: [
    { titulo: "Could Solar Radiation Pressure Explain 'Oumuamua's Peculiar Acceleration? (ApJL, 2018)", url: 'https://arxiv.org/abs/1810.11490' },
    { titulo: 'Overview of the Galileo Project (J. Astron. Instrum., 2023)', url: 'https://arxiv.org/abs/2209.02479' }
  ],
  kevin_knuth: [
    { titulo: 'Estimating Flight Characteristics of Anomalous Unidentified Aerial Vehicles (Entropy, 2019)', url: 'https://doi.org/10.3390/e21100939' }
  ],
  beatriz_villarroel: [
    { titulo: 'Exploring nine simultaneously occurring transients on April 12th 1950 (Scientific Reports, 2021)', url: 'https://www.nature.com/articles/s41598-021-92162-7' },
    { titulo: 'Transients in the Palomar Observatory Sky Survey (POSS-I) may be associated with nuclear testing and reports of UAP (Scientific Reports, 2025)', url: 'https://www.nature.com/articles/s41598-025-21620-3' }
  ],
  thomas_townsend_brown: [
    { titulo: 'Electrokinetic Apparatus (US2949550A, 1960)', url: 'https://patents.google.com/patent/US2949550A/en' },
    { titulo: 'Electrokinetic Apparatus (US3187206A, 1965)', url: 'https://patents.google.com/patent/US3187206A/en' }
  ]
};

// ── 3. CHANNELS (YouTube home + description) ─────────────────────────────────
const YOUTUBE = {
  ch_jesse_michels: { url: 'https://www.youtube.com/@JesseMichels',
    desc: 'American Alchemy — periodismo gonzo de Jesse Michels con foco técnico en propulsión y figuras heterodoxas.',
    desc_en: "American Alchemy — Jesse Michels's gonzo journalism with a technical focus on propulsion and heterodox figures." },
  ch_documental_s4_luigi_project_gravitar: { url: 'https://www.youtube.com/@ProjectGravitaurOfficial',
    desc: 'Project Gravitaur — recreación en VFX del S4 de Bob Lazar dirigida por Luigi Vendittelli.',
    desc_en: "Project Gravitaur — VFX recreation of Bob Lazar's S4, directed by Luigi Vendittelli." },
  ch_weaponized_jeremy_corbell_george_knapp: { url: 'https://www.youtube.com/@JeremyCorbell',
    desc: 'WEAPONIZED — Jeremy Corbell y George Knapp destapan testimonios de whistleblowers y los vídeos de la Navy.',
    desc_en: 'WEAPONIZED — Jeremy Corbell and George Knapp surface whistleblower testimony and the Navy videos.' },
  ch_jeremy_corbell: { url: 'https://www.youtube.com/@JeremyCorbell',
    desc: 'Canal personal de Jeremy Corbell, cineasta y divulgador de evidencia UAP.',
    desc_en: 'Personal channel of Jeremy Corbell, filmmaker and UAP-evidence investigator.' },
  ch_jason_samosa: { url: 'https://www.youtube.com/@jason_samosa',
    desc: 'Jason Samosa — series temáticas largas sobre Vallée, religión y el fenómeno.',
    desc_en: 'Jason Samosa — long thematic series on Vallée, religion and the phenomenon.' },
  ch_area52: { url: 'https://www.youtube.com/channel/UCvQ_EDuk8w67a2UkCS1ptbA',
    desc: 'Area52 / DEBRIEFED — entrevistas largas de Chris Ramsay con actores clave del campo.',
    desc_en: 'Area52 / DEBRIEFED — Chris Ramsay long-form interviews with key figures in the field.' },
  ch_the_sol_foundation: { url: 'https://www.youtube.com/@_SolFoundation',
    desc: 'The Sol Foundation — simposios académicos (Nolan, Davis, Puthoff, Nell, Loeb…).',
    desc_en: 'The Sol Foundation — academic symposia (Nolan, Davis, Puthoff, Nell, Loeb…).' },
  ch_richard_dolan_intelligent_disclosure: { url: 'https://www.youtube.com/channel/UCnaIeNm-jSa1l8yHrn7PlQg',
    desc: 'Intelligent Disclosure — análisis histórico del fenómeno por Richard Dolan.',
    desc_en: 'Intelligent Disclosure — historical analysis of the phenomenon by Richard Dolan.' },
  ch_ashton_forbes: { url: 'https://www.youtube.com/@JustXAshton',
    desc: 'Ashton Forbes — MH370, energía de punto cero y propulsión warp.',
    desc_en: 'Ashton Forbes — MH370, zero-point energy and warp propulsion.' },
  ch_uap_gerb: { url: 'https://www.youtube.com/channel/UCXr8USOuzZN_3y_efZpryrg',
    desc: 'UAP Gerb — investigador emergente con acceso directo a ex-militares.',
    desc_en: 'UAP Gerb — emerging researcher with direct access to ex-military sources.' },
  ch_newsnation: { url: 'https://www.youtube.com/@NewsNation',
    desc: 'NewsNation / Reality Check — periodismo de investigación de Ross Coulthart.',
    desc_en: 'NewsNation / Reality Check — investigative journalism by Ross Coulthart.' },
  ch_that_ufo_podcast: { url: 'https://www.youtube.com/@ThatUFOPodcast',
    desc: 'That UFO Podcast — entrevistas y actualidad del campo UAP desde el Reino Unido.',
    desc_en: 'That UFO Podcast — UAP interviews and news from the UK.' },
  ch_polarity: { url: 'https://www.youtube.com/@PolarityJosh',
    desc: 'Polarity — directos y deep-dives sobre UAP, inteligencia no humana y potencial humano.',
    desc_en: 'Polarity — live shows and deep-dives on UAP, non-human intelligence and human potential.' },
  ch_vetted: { url: 'https://www.youtube.com/@VETTEDPODCAST',
    desc: 'VETTED — investigación y verificación crítica de casos UAP.',
    desc_en: 'VETTED — critical investigation and fact-checking of UAP cases.' },
  ch_dr_steven_greer: { url: 'https://www.youtube.com/channel/UCC6B4Y0oFACv9QBlf0ebBcg',
    desc: 'Dr. Steven Greer — divulgación y el protocolo de contacto CE-5.',
    desc_en: 'Dr. Steven Greer — disclosure advocacy and the CE-5 contact protocol.' },
  ch_third_eye_drops: { url: 'https://www.youtube.com/@THIRDEYEDROPS',
    desc: 'Third Eye Drops · Michael Phillip — conversaciones sobre conciencia, fenómeno y experiencia.',
    desc_en: 'Third Eye Drops · Michael Phillip — conversations on consciousness, the phenomenon, and experience.' }
};

// ── 4. COHERENCE COMPLEMENT (extra useful info from the timeline) ────────────
// lockheed_martin_skunk_works: the data.js bio is the (factually correct, 1943)
// aviation-history writeup; the timeline adds UAP Gerb's documentary analysis.
// Append it as a complement so data.js encompasses the timeline without
// contradicting it. (Year kept at 1943 = documented Skunk Works founding.)
const BIO_APPEND = {
  lockheed_martin_skunk_works:
    '\n\nEl análisis de UAP Gerb (2024): Uno de los documentales más exhaustivos sobre Lockheed Martin examina el Tonopah Test Range como posible almacén de material recuperado, el rol de Skunk Works en programas de acceso especial de la USAF, y el Memo Wilson-Davis de 2002 — la reunión entre el almirante Thomas Wilson y el físico Eric Davis en la que Wilson describe haber sido bloqueado en el acceso a un programa de recuperación gestionado por un contratista privado cuyo perfil operativo Gerb considera consistente con Lockheed.'
};

// ── APPLY ────────────────────────────────────────────────────────────────────
let nPhotos = 0, nPapers = 0, nYt = 0, nBio = 0;
for (const node of data.nodes) {
  if (PHOTOS[node.id]) { node.photo = PHOTOS[node.id]; nPhotos++; }
  if (PAPERS[node.id]) { node.papers = PAPERS[node.id]; nPapers++; }
  if (YOUTUBE[node.id]) { node.youtube = YOUTUBE[node.id]; nYt++; }
  if (BIO_APPEND[node.id] && !node.bio.includes('UAP Gerb (2024)')) {
    node.bio = node.bio + BIO_APPEND[node.id];
    nBio++;
  }
}

const newContent = `// REDESCUBRIENDO — Dataset
// Nodes: ${data.nodes.length} — Edges: ${data.edges.length} — Threads: ${data.threads.length}
// Generado automáticamente por scripts/build-data.js. NO EDITAR A MANO.
// Para regenerar: npm run build

window.RDC_DATA = ${JSON.stringify(data, null, 2)};
`;
fs.writeFileSync(filePath, newContent, 'utf8');
console.log(`✅ enriquecido: ${nPhotos} fotos, ${nPapers} nodos con papers, ${nYt} canales con YouTube, ${nBio} bios complementadas.`);
